### ISSUE TITLE
PrimoBO: "Check string at position"

### ISSUE THREAD

**Issue by LincolnUniLTL** [primousers/primo-ve-norm#16]
Primo back office has the "Check string at position" transformation built in out of the box. Can this be replicated in XML?

**Comment by LincolnUniLTL** [comment]
Just looking at this again, "Check string at position" is a validation routine (see [here](https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/Primo/Technical_Guide/020Working_with_Normalization_Rules/060Validation_Routines)).

Given:
dc:identifier>University of X - Main Library</dc:identifier>

This XML compiles correctly and should work but comes up with a run time class error:

rule "check string at position"
when
  "substring(//*[local-name()='identifier']/text(),3,1)" equals "v"
then
copy "substring(//*[local-name()='identifier']/text(),6,2)" to "discovery"."local2"
end

Help still needed.
Craig.

**Comment by LincolnUniLTL** [comment]
Okay, so I tried this condition ... 

"//*[local-name()='identifier'][substring(text(),3,1)]"  equals "v"

The rule now compiles and runs (without error) but does not return "true" so "discovery"."local2" is not added.

Help still needed.
Craig.

**Comment by mwan-work** [comment]
Hi, in xpath the first character is '1' rather than '0'. Something like this would work:

exist //*[local-name()='identifier'][contains(substring(., 4, 1), 'v')]

but it is case sensitive and would only look for lower case 'v'.  You would have to create another line to capture the uppercase:

```
rule "Check string"
when
	exist "//*[local-name()='identifier'][contains(substring(., 4, 1), 'v')]"
	exist "//*[local-name()='identifier'][contains(substring(., 4, 1), 'V')]"
then
   
	copy  "//*[local-name()='identifier'][contains(substring(., 4, 1), 'v')]" to "dc"."identifier"
	copy  "//*[local-name()='identifier'][contains(substring(., 4, 1), 'V')]" to "dc"."identifier"

end
```

another way of ignoring case sensitivity:

```
rule "Check string"
when
	exist "//*[local-name()='identifier'][contains(translate(substring(., 4, 1), 'v', 'V'), 'V')]"
	
then
   	copy  "//*[local-name()='identifier'][contains(translate(substring(., 4, 1), 'v', 'V'), 'V')]" to "dc"."identifier"
	
end
```

Both rules will check the existence of the letter V in the 4th position, and will only copy the field(s) that meet the condition


![image](https://github.com/user-attachments/assets/758942bf-8d6a-407d-a5cc-e19af5116b37)

**Comment by LincolnUniLTL** [comment]
Hi Mike,
Perfect. This works a treat!
We'll be crediting you for this code in the wiki.
Thank you again for your help.
Cheers,
Craig.

**Comment by LincolnUniLTL** [comment]
Verified with code and wiki pages created.
